### PR TITLE
10 TB -> 10 GB: Fix metadata w/ mk-zim-cat-item.py & mk-zim-cat.py [C'est pas sorcier, CrashCourse, TED-Ed, GCFAprendeLibre]

### PR DESCRIPTION
**Pull request by holta**
@tim-moody please review before merging, to confirm this is sufficiently correct?

### CODE REVIEW

**Comment by holta** [comment]
FYI this PR is nothing more than an attempt at cleaning up the metadata for these three ~10GB ZIM files:

- https://s3.us-east-2.wasabisys.com/iiab-zims/cest-pas-sorcier_fr_top_2021-01.zim
- https://s3.us-east-2.wasabisys.com/iiab-zims/crashcourse_en_top_2021-01.zim
- https://s3.us-east-2.wasabisys.com/iiab-zims/teded_en_top_2021-01.zim

Precisely, this PR is nothing more than the automated results arising from running:

```
cd /opt/iiab-share/iiab-content/catalogs
./mk-zim-cat-item.py cest-pas-sorcier_fr_top_2021-01.zim --source https://s3.us-east-2.wasabisys.com/iiab-zims/
./mk-zim-cat-item.py crashcourse_en_top_2021-01.zim --source https://s3.us-east-2.wasabisys.com/iiab-zims/
./mk-zim-cat-item.py teded_en_top_2021-01.zim --source https://s3.us-east-2.wasabisys.com/iiab-zims/
mv cest-pas-sorcier_fr_top_2021-01.json crashcourse_en_top_2021-01.json teded_en_top_2021-01.json zim-cat-fragments
./mk-zim-cat.py
```

Concluding Questions:

- Is the above automated process good enough?
- The mangled metadata arising is each ZIM file's .json fragment below is very ugly &mdash; but seems to likely originate from the ZIM files themselves &mdash; so probably we're stuck with it for now?

```
"tags": "y;o;u;t;u;b;e;_;v;i;d;e;o;s;:;y;e;s;_ftindex:no;_pictures:yes;_videos:yes;_details:yes",
```

**Comment by holta** [comment]
ASIDE: How important is the following issue?

- #12

**Comment by holta** [comment]
Recap screenshots showing the original problem: (Admin Console ends up showing ~10 TB erroneously, when it should show ~10 GB for these 3 ZIM files)

image

image

**Comment by holta** [comment]
Another way of viewing the proposed (harmless???) SIDE EFFECTS of this PR:

image

**Comment by holta** [comment]
Note that metadata associated with these 3 ZIM files is already problematic even prior to this PR — as seen in this kiwix-serve screenshot — if you look closely:

IMG-20230118-WA0004

So I'd assume this PR does not make the situation any worse?  Hopefully @tim-moody can confirm?

**Comment by holta** [comment]
@georgejhunt can you recommend merging this PR experimentally — or another course of action if further metadata fixes are required?

**Comment by holta** [comment]
ASIDE: @deldesir asks if we can learn from @georgejhunt about any crucial-or-critical metadata hand-fixes that might be advisable in general?

Specifically, do the 3 Basic Electricity ZIM files below illustrate any tips & tricks we should learn from here?

- https://github.com/iiab-share/iiab-content/blob/main/catalogs/zim-cat-fragments/basic_elecricity_en_all_min_2020-11.json
- https://github.com/iiab-share/iiab-content/blob/main/catalogs/zim-cat-fragments/basic_elecricity_es_all_min_2020-11.json
- https://github.com/iiab-share/iiab-content/blob/main/catalogs/zim-cat-fragments/basic_elecricity_fr_all_min_2020-11.json

**Comment by holta** [comment]
ASIDE: @tim-moody you're probably aware but just FYI @deldesir did a quick survey of metadata across [all 9 of our IIAB Catalog ZIM files](https://github.com/iiab-share/iiab-content/tree/main/catalogs/zim-cat-fragments):

- "Educatonal" is misspelled at https://github.com/iiab-share/iiab-content/blob/main/catalogs/zim-cat-fragments/gcflearn_es_all_maxi_2021-03.json#L10
- Logo (favicon) is missing in some cases like GCFLearnFree ES above.  Also missing from these:
  - Basic Electricity
  - NIH Rare Diseases

**Comment by tim-moody** [comment]
>"Educatonal" is misspelled 

I probably mistyped it. Can be fixed by hand.

Not sure that we use favicon since we don't use kiwix as a front end

**Comment by tim-moody** [comment]
looks right

**Comment by holta** [comment]
> Not sure that we use favicon since we don't use kiwix as a front end

Isn't this logo/favicon automatically extracted when new menudefs are auto-created, to showcase new ZIM files on IIAB's main page?  (Or so I thought, maybe I've got this all wrong, apologies if so!)

**Comment by tim-moody** [comment]
>Isn't this logo/favicon automatically extracted when new menudefs are auto-created

not sure if we are still able to do this with the new catalog. in any event I always assumed that if we great a zim we would also create its menu def

**Comment by tim-moody** [comment]
anyway, you're right someone should check if we are doing this with the new catalog and implement it if not. These logos look to be 48px x 48, which is a little small, but better than nothing. probably @deldesir could figure it out.

**Comment by holta** [comment]
@tim-moody after this PR (or similar) is merged, can users see the new ZIM catalog by logging back in to Admin Console, and/or by clicking "Refresh Kiwix Catalog" ?

image

(Or is a fresh install of IIAB & Admin Console likely necessary?)

**Comment by tim-moody** [comment]
just refresh catalog

**Comment by holta** [comment]
I tried contacting @georgejhunt directly for his recommendations here.  No luck so far, since Wednesday.  He should have good ideas.  In any case, I suggest we move forward with this PR allowing for community testing &mdash; and amend it later wherever George and users can offer further improvements.

**Comment by tim-moody** [comment]
I agree

**Comment by holta** [comment]
Looks great.
Hopefully @deldesir and others can confirm.
Fresh installs of all 4 ZIM files can't hurt to verify!

**Comment by tim-moody** [comment]
>Fresh installs of all 4 ZIM files can't hurt to verify!

would verify that source url not broken

**Comment by holta** [comment]
> > Fresh installs of all 4 ZIM files can't hurt to verify!
>
> would verify that source url not broken

First fresh install doesn't seem to work: @tim-moody is it unrelated that jobs are marked "SCHEDULED" but never begin?

image

I rebooted and that does not help.  Waiting 10min also did not help.  FYI this is Debian 12 (currently in pre-release freeze, and generally reliable in other regards).  Feel free to login to 10.8.0.38 if that helps understand why it's stuck?

**Comment by tim-moody** [comment]
can't login

**Comment by holta** [comment]
http://10.8.0.46/admin (Ubuntu 22.04) appears to have the very same problem.

Can you log into either?  (Or if not, any idea why?)

**Comment by tim-moody** [comment]
can log into admin but not ssh as my key not supported

**Comment by holta** [comment]
> can log into admin but not ssh as my key not supported

Your ssh key should be supported on both VM's (mine works).  Any idea what's happening?

**Comment by tim-moody** [comment]
mine doesn't on either

**Comment by holta** [comment]
> mine doesn't on either

Hopefully when you're logged in as iiab-admin you can diagnose (why your ssh key is suddenly not working?)

**Comment by holta** [comment]
Just FYI iiab-cmdrv.service appears to be running fine on both VM's:
(below is from Debian 12 VM 10.8.0.38; Ubuntu 22.04 VM 10.8.0.46 is equivalent)

```
root@box:~# systemctl status iiab-cmdsrv
● iiab-cmdsrv.service - Provides the IIAB Command Server
     Loaded: loaded (/etc/systemd/system/iiab-cmdsrv.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-01-22 11:49:52 EST; 35min ago
    Process: 687 ExecStart=/opt/admin/cmdsrv/iiab-cmdsrv3.py --daemon (code=exited, status=0/SUCCESS)
   Main PID: 897 (iiab-cmdsrv3.py)
      Tasks: 9 (limit: 2316)
     Memory: 86.7M
        CPU: 8.761s
     CGroup: /system.slice/iiab-cmdsrv.service
             └─897 /usr/bin/python3 /opt/admin/cmdsrv/iiab-cmdsrv3.py --daemon

Jan 22 11:55:37 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-ADM-CONF.
Jan 22 11:55:37 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-VARS.
Jan 22 11:55:37 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-ANS.
Jan 22 11:55:37 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-IIAB-INI.
Jan 22 11:55:37 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-ZIM-STAT.
Jan 22 11:55:38 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-OER2GO-STAT.
Jan 22 11:55:38 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-OSM-VECT-STAT.
Jan 22 11:55:38 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-SPACE-AVAIL.
Jan 22 11:55:38 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-EXTDEV-INFO.
Jan 22 11:55:48 box IIAB-CMDSRV[897]: IIAB-CMDSRV : Received CMD Message GET-JOB-STAT {"last_rowid":1}.
```

**Comment by tim-moody** [comment]
adm cons doesn't think kiwix is installed, so is waiting for it

if you install from a preset kiwix will be installed, but otherwise you have to check it in configure and ico

**Comment by holta** [comment]
1) On 10.8.0.38 installing Kiwix and then restarting iiab-cmdsrv got things moving, thanks for solving that!

2) And then it moved TED-Ed from /libary/working/zims as soon as the 78MB nih_rarediseases_en_all_maxi_2020-12.zim was done downloading i.e. when the download of teded_en_top_2021-01.zim was only 3% complete!

image

Any idea why this is happening?

FYI /library/zims/content/teded_en_top_2021-01.zim continues to expand (presumably as a result of the wget command keeping the file handle, despite the destination having moved!)  Is this A-Ok ??

**Comment by tim-moody** [comment]
what I said was with regard to .46. I see that .38 now has kiwix installed and the zim downloads have started and in one case succeeded.

**Comment by tim-moody** [comment]
The only thing I can think of is that the restart logic doesn't handle job dependencies properly.

**Comment by tim-moody** [comment]
Also though jobs 3 and 4 say succeeded, the zim was not added, and the job output even says that. On checking I see that rare diseases did get added, but not to menu

**Comment by holta** [comment]
> Also though jobs 3 and 4 say succeeded, the zim was not added, and the job output even says that. On checking I see that rare diseases did get added, but not to menu

I noticed that.

Weird that neither ZIM file appears on the IIAB home page so far.

(Certainly I can manually force these later, i.e. after the 10GB TED-Ed is downloaded, I can run `iiab-make-kiwix-lib` or click **Install Content > Reindex Kiwix Content** -- and then run `iiab-update-menus`)

Hopefully these kinds of things are a very rare occurrence arising from `systemctl restart iiab-cmdsrv` ?

**Comment by tim-moody** [comment]
>Hopefully these kinds of things are a very rare occurrence arising from systemctl restart iiab-cmdsrv ?

That's what I'm hoping. Just looking at the restart code to see if anything jumps out. Is it possible that wget continued even when you restart cmdsrv? i.e. there was no reboot

**Comment by holta** [comment]
> Is it possible that wget continued even when you restart cmdsrv?

The only thing I did was `systemctl restart iiab-cmdsrv` to try to force both wget's to begin.

I did not reboot.  (Should I have rebooted instead?)

**Comment by tim-moody** [comment]
restart assumes a cold start after a shutdown or crash

**Comment by tim-moody** [comment]
teded download is marked STARTED in the db, seems like we had a job that was still running at the OS level, but not at the cmdsrv level. don't know what that would do.

**Comment by holta** [comment]
> Weird that neither ZIM file appears on the IIAB home page so far.

Just FYI neither ZIM file appeared on the IIAB main page http://10.8.0.38 in the end.

And just 1 of 2 appears at http://10.8.0.38/kiwix/ in the end.

image

(I can manually force the fixing of all the small issues above, as mentioned earlier, so I'm only mentioning this as an FYI.)

**Comment by holta** [comment]
> teded download is marked STARTED in the db, seems like we had a job that was still running at the OS level, but not at the cmdsrv level. don't know what that would do.

Time to repeat the experiment on 10.8.0.46 == Ubuntu 22.04 just for kicks?

(Do you want to do that...or should I?)

**Comment by tim-moody** [comment]
reboot .46 first as I have cmdsrv running manually

**Comment by holta** [comment]
- I rebooted .46
- I ran `./runrole kiwix` to install kiwix-tools successfully.

I don't know how to check the DB for individual jobs' status (do you want to do this, then restart the VM to see how it goes?)

**Comment by tim-moody** [comment]
there might be a logical flaw in cmdsrv 3634ff if the job is the highest number, has no dependencies, but is itself dependent.

**Comment by holta** [comment]
> there might be a logical flaw in cmdsrv 3634ff

Is 3634ff a particular commit?  Am I looking in the wrong repo if so (am not seeing it!)

**Comment by tim-moody** [comment]
sorry is a line number and I don't know how you do the fancy L# url

**Comment by holta** [comment]
These lines below?  (Click ellipsis on left, if you want either kind of URL...)

- https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/files/iiab-cmdsrv3.py#L3634-L3651
- https://github.com/iiab/iiab-admin-console/blob/fb00fe88d28fd167175b1409e0447cfb6cb336f7/roles/cmdsrv/files/iiab-cmdsrv3.py#L3634-L3651

image

**Comment by tim-moody** [comment]
https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/files/iiab-cmdsrv3.py#L3566

is the function

yeah was just doing it

**Comment by tim-moody** [comment]
>I ran ./runrole kiwix to install kiwix-tools successfully.

since this was after reboot, cmdsrv may not know about it unless you restart it and refresh admin

**Comment by holta** [comment]
> > I ran `./runrole kiwix` to install kiwix-tools successfully.
> 
> since this was after reboot, cmdsrv may not know about it unless you restart it and refresh admin

I rebooted .46 (Ubuntu 22.04).

The behavior is identical to .38 (Debian 12).

(In each case, `zim_install_move.sh teded_en_top_2021-01.zim` is run prematurely, triggered by a different ZIM file download's completing.)

**Comment by tim-moody** [comment]
This is how it should work if kiwix is installed using Admin Console even after the zim downloads are scheduled.

image

And they were properly added to the home menu.

image

**Comment by deldesir** [comment]
FYI, I removed all ZIM files via admin console (Install content > Manage content > Remove selected content) and redownload them using Admin console again. I monitored the commands jobs and all succeed. I can access all the ZIM via Kiwix. No service restart was needed.

**Comment by tim-moody** [comment]
@deldesir perfect. thanks for confirming.

**Comment by holta** [comment]
> 2\. And then it moved TED-Ed from /libary/working/zims as soon as the 78MB nih_rarediseases_en_all_maxi_2020-12.zim was done downloading i.e. when the download of teded_en_top_2021-01.zim was only 3% complete!

Above issue is confirmed fixed!  Thanks to @tim-moody's:

- PR iiab/iiab-admin-console#523

**Pull request merged**
