### PR TITLE
Ghadds -- 

### PR DESCRIPTION
**Pull request by georgejhunt**
I don't really know how to test this, except to merge it and test it -- backing out the PR if it fails

### CODE REVIEW

**Comment by tim-moody** [comment]
>I don't really know how to test this, except to merge it and test it -- backing out the PR if it fails

not really possible to test a branch with a lot of changes

**Comment by holta** [comment]
Merged on @georgejhunt's request, after he tested this, as mentioned during this morning's call.

**Comment by holta** [comment]
@georgejhunt can you look into problems @tim-moody says are arising from this PR?

> unicode is messed up in iiab-content #4 e.g.  "title": "\u00c9lectricit\u00e9 de base", (there are others)

> the original was "title": "Électricité de base"

**Comment by tim-moody** [comment]
I am investigating to verify the problem. 
I am also not seeing the new zims in the catalog in adm cons.

**Comment by tim-moody** [comment]
Drilling down, I see this may be cosmetic, but we should still try to fix it at some point:

https://github.com/iiab-share/iiab-content/blob/main/catalogs/iiab-zim-cat.json has

"6ad87d7f-75b7-ebd3-a660-340eb6fad212": {
    "path": "../library/zims/content/cest-pas-sorcier_fr_top_2021-01.zim",
    "title": "C'est pas sorcier",
    "description": "Magazine t\u00e9l\u00e9visuel de vulgarisation scientifique destin\u00e9 aux enfants",
  ...

Adm Cons renders this as

image

which is correct.

  Électricité de base (basic_elecricity_fr_all_min) looks OK too.

"6803b18b-cefa-e85c-220e-8189aaf48970": {
    "path": "../library/zims/content/basic_elecricity_fr_all_min_2020-11.zim",
    "title": "\u00c9lectricit\u00e9 de base",

**Comment by tim-moody** [comment]
This cosmetic problem can be avoided by using

https://github.com/iiab-share/iiab-content/blob/main/catalogs/mk-zim-cat-item.py

to create the zim catalog fragment.

**Comment by tim-moody** [comment]
Also please note that the catalog contains language code fr, which should be fra as Kiwix uses the non-standard codes eng, fra, spa for those languages. This is in the zim itself, which is the source of the zim fragment, and must be used when the zim is created.

**Pull request merged**
